default[:nexus][:user] = "nexus"
default[:nexus][:group] = "nexus"
default[:nexus][:url] = "http://nexus.sonatype.org/downloads/nexus-oss-webapp-1.9.1-bundle.tar.gz"
default[:nexus][:home] = "/opt/nexus"
default[:nexus][:directory] = "nexus-oss-webapp-1.9.1"
default[:nexus][:work] = "/data/nexus-work"
