source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-reloader'
gem 'erubis'
gem 'tilt'
gem 'activerecord'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-sqlite-adapter'
gem 'activesupport'
gem 'sqlite3'
gem 'less'
gem 'thin'
gem 'bcrypt-ruby', :require => 'bcrypt'
