#
#

require 'pathname'
require 'rubygems'
require 'json'

task :default do
  sh "cd config && ruby dna.rb"
end

namespace :cook do
  dir = File.dirname(__FILE__)

  Pathname.new(dir).join("config").children.each do |e|
    next unless e.basename.to_s =~ /dna-(\w+).json/
    name = $1
    task name => :default do
      sh "chef-solo -c #{dir}/config/solo.rb -j #{e}"
    end
  end

  task :lexy => :default do
    sh "chef-solo -c #{dir}/config/solo.rb -j /etc/lexy.chef.json"
  end

  task :custom => :default do
    dna = {
      "recipes" => ENV['recipes'].split(',')
    }
    File.open("config/dna-custom.json", "w") do |f|
      f.write(dna.to_json)
    end
    sh "chef-solo -c #{dir}/config/solo.rb -j #{dir}/config/dna-custom.json"
  end
end

# EOF
