#
#

require 'pathname'
require 'rubygems'
require 'open-uri'
require 'json'

class EC2
  def self.security_groups
    open("http://169.254.169.254/latest/meta-data/security-groups/").read.split("\n")
  end

  def self.ip
    open('http://169.254.169.254/latest/meta-data/public-ipv4').read
  end
end

task :default do
  dir = File.dirname(__FILE__)
  Pathname.new(dir).join("config").children.each do |e|
    next unless e.basename.to_s =~ /dna.*\.rb/
    sh "cd config && ruby #{e}"
  end
end

namespace :cook do
  dir = File.dirname(__FILE__)

  Pathname.new(dir).join("config").children.each do |e|
    next unless e.basename.to_s =~ /dna-(\w+).json/
    name = $1
    task name => :default do
      sh "chef-solo -c #{dir}/config/solo.rb -j #{e}"
    end
  end

  task "security-groups" => :default do
    EC2.security_groups.each do |name|
      file = Pathname.new(dir).join("config").join("dna-" + name + ".json")
      next unless file.file?
      sh "chef-solo -c #{dir}/config/solo.rb -j #{file}"
    end
  end

  task :custom => :default do
    dna = {
      "recipes" => ENV['recipes'].split(',')
    }
    File.open("config/dna-custom.json", "w") do |f|
      f.write(dna.to_json)
    end
    sh "chef-solo -c #{dir}/config/solo.rb -j #{dir}/config/dna-custom.json"
  end

  task :lexy => :default do
    sh "chef-solo -c #{dir}/config/solo.rb -j /etc/lexy.chef.json"
  end
end

# EOF
